# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D7ryKFXpDT-oT9zRWtVEy_nbSLixhP6r
"""

import numpy as np
from flask import Flask, request, jsonify, render_template
import joblib
import requests

app = Flask(__name__)
model = joblib.load("power_prediction.sav")

@app.route('/')
def home():
    return render_template("intro.html")

@app.route('/predict')
def predict():
    return render_template("predict.html")

@app.route('/windapi', methods=['POST'])
def windapi():
    city = request.form.get('city')
    apikey = "d8484354b9e388875c48dae8d0d09cd1"
    url = "http://api.openweathermap.org/data/2.5/weather?q=" + city + "&appid=" + apikey
    resp = requests.get(url)
    resp = resp.json()
    temp = str(resp["main"]["temp"]) +" °C"
    humid = str(resp["main"]["humidity"]) + " %"
    pressure = str(resp["main"]["pressure"]) + " mmHG"
    speed = str(resp["wind"]["speed"]) + " m/s"
    return render_template('predict.html', temp=temp, humid = humid, pressure=pressure, speed = speed)

@app.route('/y_predict',methods = ['POST'])
def y_predict():
    x_test = [[float(x) for x in request.form.values()]]
    
    prediction = model.predict(x_test)
    print(prediction)
    output = prediction[0]
    return render_template('predict.html',prediction_text = 'The energy predicted is {:.2f} KWh'.format(output))

if __name__ == "__main__":
    app.run(debug=False)